global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'prometheus_frigate_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus_frigate_exporter:9104']

  - job_name: 'nginx_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: "bb_mac_exporter"
    static_configs:
      - targets: ['bb.local.drugyacht.com:9100']

  - job_name: immich_api
    static_configs:
      - targets: ['immich_server:8081']

  - job_name: immich_microservices
    static_configs:
      - targets: ['immich_server:8082']

  - job_name: immich_stats
    static_configs:
      - targets: ['immich_exporter:3000']

  - job_name: 'iperf3'
    scrape_interval: 15m
    metrics_path: /probe
    static_configs:
      - targets:
        - bb.local.drugyacht.com
    params:
      port: ['5201']
      # Optional: enable reverse mode
      # reverse_mode: ['true']
      # Optional: enable UDP mode
      # udp_mode: ['true']
      # Optional: set bitrate limit
      # bitrate: ['100M']
      # Optional: set test period
      # period: ['10s']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: iperf3_querier_exporter:9579  # The iPerf3 exporter's real hostname:port.
    
  - job_name: 'speedtest-probe'
    scrape_interval: 60m
    scrape_timeout: 45s
    metrics_path: /probe
    static_configs:
    - targets:
      - prometheus_speedtest:9516

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
